# Abstract {-}

This research consists of an examination of the relationships between electoral socio-demographic characteristics and two-party preference in Australian federal elections, with the six elections from 2001 to 2016 considered. Socio-demographic information is derived from the Australian Census, and calculated for each electorate in each election using a spatio-temporal method of imputation. Several strategies, including an information-theoretic approach, are adopted to select the most important variables to include in a cross-sectional model specification used for each election. The selected set of socio-demographics relate to, amongst others, education, age, country of birth, single parent households, certain job types and religious affiliation. Insights regarding the changing effects of these variables are obtained using visualisation tools from various `R` packages. Consistent relationships between electoral two-party preference and all socio-demographic characteristics are found across elections, with exceptions being religiousness, and a combination of an older age profile with low education levels. All data processed in this study will be contributed to the existing `eechidna` `R` package.







<!--
The following line is required to re-set page numbering after preliminary material. Do not remove
-->
\clearpage\pagenumbering{arabic}\setcounter{page}{1}
