# Introduction {#ch:intro}

Australia has changed in many ways over the last two decades. Rising house prices, country-wide improvements in education, an ageing population, and a decline in religious affiliation, are just a few facets of the country's evolving socio-demographic characteristics[^1]. At the same time, political power has moved back and forth between the two major parties. In the 2007 and 2010 federal elections, the Australian Labor Party (Labor) was victorious, whereas the 2001, 2004, 2013 and 2016 elections were won by the Liberal National coalition (Liberal). A measure of support between these two parties is the two-party preferred vote, which has been as high as 53.5% and as low as 47.3% in favour of the Liberal party over the six elections.

The simultaneous changes in characteristics of the Australian population and preference between the two parties lead to our research question, *What socio-demographic characteristics are key determinants of electorate support between the Labor and Liberal parties, and how have their effects changed over time?*

Previous studies of Australian federal elections have shown that socio-demographic characteristics (simply, socio-demographics) are good predictors of party support, at an aggregate level. However, as far as we can see, these studies do not venture beyond the 2007 election. Adding to the existing research, this thesis explores the dynamics of electorate party preference for the six federal elections between 2001 and 2016, using a statistical framework. The two-party preferred vote is the outcome of interest, and is modelled as a function of electorate socio-demographics. An emphasis is placed on understanding how the effects of socio-demographics have changed over time.

The socio-demographic information is obtained from the Australian Census of Population and Housing (Census), a country-wide survey conducted every five years. Federal elections are generally conducted every three years. There are 150 electorates in Australia, with each corresponding to a single seat in the federal House of Representatives. It is electorates that ultimately determine the result of an Australian federal election[^2], which is why electorates are chosen as the level of aggregation for this study. Therefore, the information used in this study consists of the electoral two-party preferred vote, and Census data aggregated to Commonwealth Electoral Divisions, which is an approximation of the electorate boundaries.

The two-party preferred vote and the socio-demographic data from the Census possess a temporal component and a spatial component, as both are observed at particular points in time and are aggregate measures for a set of regions in Australia. Census and elections often occur in different years, and electoral boundaries change frequently. Therefore, in order to match socio-demographic information from the Census with the electoral two-party preferred vote for each election, a method of spatio-temporal imputation is required. The method used in this study involves estimating an electorate's socio-demographic composition at the time of a Census, using an areal imputation approach, and then linearly interpolating between Census years to approximate the socio-demographics of that electorate, at the time of the election. To adjust for changing variable scales across elections, each socio-demographic variable is centered to have a mean of zero and standardized to have a variance of one, within each election. The resultant cross-sectional data set for each election consists of $n=150$ electorates (observations) and $p=63$ socio-demographic (explanatory) predictors.

Each election is modelled separately with a consistent model specification. This avoids imposing a time-invariant restriction on any regressor, and allows for socio-demographic effects to be compared across elections. In order to obtain the desired model specification, steps are taken to reduce the dimension of the data set, as a large number of predictors $p=63$ and relatively small sample size $n=150$ is problematic. 

The first step in dimension reduction involves grouping similar socio-demographic variables together into *factors*. Principal component analysis of socio-demographic variables is employed to determine which variables should be grouped, by identifying variables that have large loadings in one the first four components. Factors are also centered and standardized. The result is a reduced set of $p=30$ predictors. From this reduced set, all possible five variable linear models are fit for each election, with the two-party preferred vote as the response. These models form a set for which Akaike weights are calculated, providing a measure relative variable importance for that election. Using this information-theoretic technique, the five most important variables are identified for each of the six elections. A superset is formed by taking the union of these important socio-demographics, which results in a set of ten variables.

The final specification consists of regressing the two-party preferred vote on the superset of ten predictors and four two-way interactions. Each election model is estimated separately using ordinary least squares. Insights are then found by visualizing the socio-demographic effects within each election. The estimated main effects are described using partial residual plots, and two-way interactions are illustrated with two-dimensional contour plots.

To guide the reader through each step of the analysis, this thesis is structured as follows. Section \@ref(ch:litreview) contains a literature review of Australian federal elections modelled using Census information. The data used in this study and the imputation process are described in Section \@ref(ch:Data). The steps involved in choosing a statistical model, reducing the dimension of the data, selection of the most important socio-demographic variables, and the final model specification, are explained in Section \@ref(ch:Modelling). Section \@ref(ch:Insights) contains the insights from the final estimated models. The conclusion and a discussion of possible extensions are detailed in Section \@ref(ch:Conclusion).

All content produced in this study is reproducible, and the (imputed) election cross-sectional data sets have been made publicly available, making this project a resource for future research. A key deliverable is the contribution made to the existing `eechidna`[^3] `R` package, which includes the GIS maps, data from all Censuses and elections, and the imputed socio-demographic electorate profiles at the time of each election. When future elections and Censuses come around, the `eechidna` package will provide a resource for anyone wishing to conduct their own socio-political analysis. 

[^1]: Socio-demographics are characteristics of a population, such as the distributions of age, gender, ethnicity, education level and income. 
[^2]: The party that wins support from a majority of seats in the House of Representatives forms the government.
[^3]: The name `eechidna` is an acronym for 'Exploring Election and Census Highly Informative Data Nationally for Australia'.
