# Literature review {#ch:litreview}

## Previous work on Australian federal elections

There exist few studies that conduct an econometric analysis of Australian federal elections using socio-demographic information. Due to the inherent asynchronicity of elections and Censuses, the most common approach is to pair data from the nearest Census to the election of interest using GIS. This can be done for any level of statistical aggregation, however the predominant approach is to connect Census collection districts to the nearest polling booth, as done in @DavisStimson98, @Forrest01, @Stimson06 (later adopted to an online e-research platform in @Liao09) and @Stimson09. Our study is focused on electorates, which is a greater level of aggregation than used in these studies, so we opt for different method of estimating Census information at election time. @Goodchild1993 illustrates a framework for areal imputation, with *piecewise approximation* being most appropriate for our problem.

As far as we know, a regression framework has only been applied to this context on two occasions. @Forrest01 uses multiple regression to identify significant determinants of the primary vote for each party the Farrer electorate in the 1998 election, by modelling each party's share of primary votes as a separately using ordinary least squares (OLS). The adjusted R-squared obtained in these regressions ranged from 0.158 to 0.785, suggesting that some parties (incluing Labor and Liberal parties) are more predictable than others. They found that age, education and migrant populations were influential in determining support for both Labor and Liberal. @Stimson09 also applies a multiple regression framework to party preference, by modelling the swing vote in the 2007 election. Resultant models were relative poor fits (adjusted R-squared of 0.223), and as such no insights about socio-demographic effects were found. Both of these studies use a stepwise procedure to obtain a model on a reduced variable set, and had limited success in providing rich insights into socio-demographic preferences.

Another method to differentiate between party preference is to use principal component analysis on the socio-demographic variables, as in @Stimson06, @Stimson09 and @Stimson12. Electorates are assigned to a particular party based on their primary vote, and each party is then summarized by its mean z-scores in the directions of the first two principal components. For the 2001, 2004 and 2007 elections, the Labor party was found to be appealing to lower income, younger and more multicultural areas, whereas the Liberal party was assocated with higher income, older and more mono-cultural areas [@Stimson12]. Whilst we do not assign parties in this way, we do use principal components to understand which variables appear grouped together.

Other election related studies that apply a similar framework predominantly model individual voter behaviour using survey data (see @Schram92, @Wilson2011 and @Gibson2011).

Seemingly absent from Australian studies is the examination of socio-political relationships using in a regression framework, over time. It also appears that no study has attempted any type of econometric analysis of socio-demographics and voter behaviour in Australia since 2007. This study covers the six Australian federal elections in the 21st century. We also note that all of these studies have paired electorate information (votes) with Census information (socio-demographics) from a single year. In this study we propose a method of spatial imputation for the election years without a Census that accounts for both temporal and spatial components of electorates by using information from the nearest Censuses on either side of the election.

## An information-theoretic approach to variable selection

Our modelling approach consists of six separate cross-sectional models - one for each election. With over 50 variables derived from Census data, we adopt an information-theoretic approach of Akaike weights to conduct variable selection from @BurnhamAnderson2002. Fundamentally based on the work of @Akaike73, the sum of Akaike weights can be compared across variables to infer relative variable importance. This is a common approach used in ecological studies (see @Johnson2004 and @Symonds2011).
