# Modelling {#ch:Modelling}

## Superset Models

Now that we have our variable set, we run an OLS regression for each election year, with $TPP$ as the response.

The models are estimated




## Model diagnostics

ADD DIAGNOSTICS TO MODELLING SECTION

Residuals are inspected for any signs of non-normality using a QQ plot, and we plot the residuals against the fitted values to detect the presence of residual heteroskedasticity. Non

Residual normality, residual heteroskedasticity, non-linearities (patterns in the residuals vs predictors), residuals vs predictors not in model, influence (cook distance), leverage (hat).

Tests for high leverage and goodness of fit will be done for election. Cook's distance will be used to identify points with high influence,  will determine whether particular electorates are outliers from the rest, in terms of the relationship between socio-demographics and voting behaviour. Tests for high leverage to be conducted will include Cook's distance and Likelihood distance [@RC82].

Goodness of fit tests will determine how well the data fits the imposed model structure. Tests will include Pearson's Chi-Square and Aitchison's ${\text R}^2$ measure of total variability [@JA86].
