---
title: "Skeleteon of Thesis Structure"
output: html_notebook
---

# What makes Australians vote the way they do? A socio-demographic study of federal elections.

## Acknowledge

## Declaration

## Abstract

To be written last


## Introduction

Motivation

State the question to be answered

Why electorate level of aggregation is good!

Outline the techniques that are going to be used

## Literature review

Previous Australian election studies

Variable importance - Akaike weights


## The data

State the data sources

Explain electorate structure + imputation required

Census data

- Sourcing

- Description of explanatory variables

- Insights on changing Australian demographic [moved to end of data]

A note on Census non-response

Election data

- Explain two-party preferred

- Timeline

- Imputation

  + Mention the comparison of imputation between Census aggregation of divisions and postal areas

Standardize data

Summary statistics
- Plots to describe socio-demographic trends across elections
- Both standardized and raw
- Do this for the variables that are in the model (see section X)


## Modelling the two-party preferred

The model

- TPP: don't need to double up here

- Using OLS - why have we used this

- Why we didn't choose longitudinal (can't treat as same unit over time). Pooled analysis of cross-sections. You could pool but then you would lost time varying effects. ***


Dimension reduction

- Outline the steps

- Factor creation

  + Theory and idea
  
  + Results
  
- Top 5 variables

  + Theory 
  
  + More discussion about why we have done all 5 variable models - something about the incremental gain in AIC trailing off around 5 (need to look into this)
  
  + Results
  
  + We capture the most important! 
  
  + Discussion of omitted variables, and that most of their information is included. By construction, we have captured the most important predictors in each election, so any omitted variable bias will be negligible. Most of the omitted variables are mostly explained by those contained in the regression (R-squared). Look at top 3 examples. Those with low R-squared are not well explained by the predictors, but also do not have an impact on two-party preferred vote.** 

  
Interactions

- Procedure

Final model

- Written equation

- Estimated coefficents

## Interpretation?

Explain how we are going to conduct inference using visreg.

Main effects

- Raw data scatterplots (Variable vs. TPP) and what our expectations are

- 95% confidence bands + visreg

- Conclusions on each effect

Interactions

- Raw scatterplots

- Conclusions on each effect

Diagnostics

- Residuals

  + Normal
  
  + Non-linearities and omitted variables
  
- Influence

  + High influence points (cook distance)
  
- Goodness of fit

  + Fitted vs. actual and adjusted R-squared
  
A typical electorate
- Across the years

## Conclusion

Recap the motivation and method

Recap of the main insights

Relative socio-demographic drivers are consistent across elections

Contributions
- Analysis over time
- Collation of data being made available


## Extensions and Caveats
Spatial correlation in errors

Different level of aggregation for imputation

Different level of aggregation for analysis

Other possible questions that could be answered with the data, e.g. Swing vote


## Where to include?




## Other stuff to add - think about questions asked 

Speak with Klaus about spatial imputation - get references.




## Formatting / Manual for AMS math
- Examples of aligning writing
- `amsldoc`

Don't need 3 dps for model output
- All 6 models on 1 page


### Order

Begin with conclusion
